=== aron123/XML-assignment/libraryDatabase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Kiss Áron, UHV61T -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" >
    <xs:complexType name="passwordType">
        <xs:sequence>
            <xs:element name="hash" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="salt" type="xs:string"></xs:attribute>
    </xs:complexType>
    
    <!-- empty element -->
    <xs:complexType name="profileImage">
        <xs:attribute name="src" type="xs:string"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="personInformation">
        <xs:sequence>
            <xs:element name="name" type="xs:string"></xs:element>
            <xs:element name="email" type="xs:string"></xs:element>
            <xs:element name="mobileNumber" type="xs:string"></xs:element>
            <xs:element name="image" type="profileImage"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="userType" id="username">
        <xs:complexContent>
            <!-- extension -->
            <xs:extension base="personInformation">
                <xs:sequence>
                    <xs:element name="id" type="xs:ID"></xs:element>
                    <xs:element name="username" type="xs:string"></xs:element>
                    <xs:element name="password" type="passwordType"></xs:element>
                    <xs:element name="info" type="personInformation"></xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="librarianType">
        <xs:sequence>
            <xs:element name="employeeID" type="xs:ID"></xs:element>
            <xs:element name="salary" type="xs:int"></xs:element>
            <xs:element name="userID" type="xs:IDREF"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="readerType">
        <xs:sequence>
            <xs:element name="id" type="xs:ID"></xs:element>
            <xs:element name="userID" type="xs:IDREF"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="genreType" final="restriction">
        <!-- restriction -->
        <xs:restriction base="xs:string">
            <xs:enumeration value="Scifi"></xs:enumeration>
            <xs:enumeration value="Crimi"></xs:enumeration>
            <xs:enumeration value="Natural"></xs:enumeration>
            <xs:enumeration value="Fiction"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="ISBN" type="xs:ID"></xs:element>
            <xs:element name="author" type="xs:string"></xs:element>
            <xs:element name="title" type="xs:string"></xs:element>
            <xs:element name="publishYear" type="xs:int"></xs:element>
            <xs:element name="genre" type="genreType"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="bookInstanceType">
        <xs:sequence>
            <xs:element name="inventoryNo" type="xs:long"></xs:element>
            <xs:element name="bookISBN" type="xs:IDREF"></xs:element>
            <xs:element name="isLoaned" type="xs:boolean"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="borrowStatusType" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BORROWED"></xs:enumeration>
            <xs:enumeration value="RETURNED"></xs:enumeration>
            <xs:enumeration value="EXPIRED"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="borrowingType">
        <xs:sequence>
            <xs:element name="id" type="xs:ID"></xs:element>
            <xs:element name="creationDate" type="xs:date"></xs:element>
            <xs:element name="expirationDate" type="xs:date"></xs:element>
            <xs:element name="status" type="borrowStatusType"></xs:element>
            <xs:element name="readerID" type="xs:IDREF"></xs:element>
            <xs:element name="bookInstanceInventoryNo" type="xs:IDREF"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="database">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="user" type="userType" ></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="librarians">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="librarian" type="librarianType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="readers">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="reader" type="readerType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="book" type="bookType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="bookInstances">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="bookInstance" type="bookInstanceType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="borrowings">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="borrowing" type="borrowingType"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="userKey">
            <xs:selector xpath="userType/id"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="bookKey">
            <xs:selector xpath="bookType/ISBN"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="bookInstanceKey">
            <xs:selector xpath="bookInstanceType/inventoryNo"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:key name="borrowingKey">
            <xs:selector xpath="borrowingType/id"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:key>
        <xs:keyref refer="bookKey" name="instanceToBookRef">
            <xs:selector xpath="bookInstanceType/bookISBN"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
        <xs:keyref refer="bookInstanceKey" name="borrowingToInstanceRef">
            <xs:selector xpath="borrowingType/bookInstanceInventoryNo"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
        <xs:keyref refer="userKey" name="readerToUserRef">
            <xs:selector xpath="readerType/userID"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
        <xs:keyref refer="userKey" name="librarianToUser">
            <xs:selector xpath="librarianType/userID"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== aron123/XML-assignment/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="libraryDatabase.xsd">
    <users>
        <user>
            <name>Toth Ferenc</name>
            <email>tf@example.com</email>
            <mobileNumber>06301234567</mobileNumber>
            <image src="https://example.com/img1.jpg"/>
            <id>ID-1</id>
            <username>tf</username>
            <password>
                <hash>$2a$04$Pd3yH9dGEf6UTZli5s2M2O3.10rx0rJKDSSwuZjidZ6Tepch.agGm</hash>
            </password>
        </user>
        <user>
            <name>Kovacs Lajos</name>
            <email>kl@example.com</email>
            <mobileNumber>06307654321</mobileNumber>
            <image src="http://img.example.com/img.png"/>
            <id>ID-2</id>
            <username>kovla</username>
            <password>
                <hash>$2a$04$7I0jg853YVVp8VDf1u6.fubfuNJ0D7bAmuHTAZddHEQyN1sS8cJi2</hash>
            </password>
        </user>
        <user>
            <name>Nagy Geza</name>
            <email>nagy@example.com</email>
            <mobileNumber>06201236547</mobileNumber>
            <image src="https://google.com/logo.png"/>
            <id>ID-3</id>
            <username>nagyg</username>
            <password>
                <hash>$2a$04$qM38KQNWMym.FCY4k9zK4eS/RXUVCg1XVfPLvfDdW20U0CzMu5ZzW</hash>
            </password>
        </user>
    </users>
    
    <librarians>
        <librarian>
            <employeeID>ID-4</employeeID>
            <salary>125000</salary>
            <userID>ID-1</userID>
        </librarian>
        <librarian>
            <employeeID>ID-5</employeeID>
            <salary>250000</salary>
            <userID>ID-2</userID>
        </librarian>
    </librarians>
    
    <readers>
        <reader>
            <id>ID-6</id>
            <userID>ID-1</userID>
        </reader>
        <reader>
            <id>ID-7</id>
            <userID>ID-3</userID>
        </reader>
    </readers>
    
    <books>
        <book>
            <ISBN>ISBN-12345678</ISBN>
            <author>Pasztor Imre</author>
            <title>Analizis 8.</title>
            <publishYear>2017</publishYear>
            <genre>Scifi</genre>
        </book>
        <book>
            <ISBN>ISBN-87654321</ISBN>
            <author>Toth Palne</author>
            <title>OS vizsga elsore</title>
            <publishYear>2016</publishYear>
            <genre>Fiction</genre>
        </book>
    </books>
    <bookInstances>
        <bookInstance>
            <inventoryNo>IN-123456</inventoryNo>
            <bookISBN>ISBN-12345678</bookISBN>
            <isLoaned>true</isLoaned>
        </bookInstance>
        <bookInstance>
            <inventoryNo>IN-123457</inventoryNo>
            <bookISBN>ISBN-12345678</bookISBN>
            <isLoaned>false</isLoaned>
        </bookInstance>
        <bookInstance>
            <inventoryNo>IN-123458</inventoryNo>
            <bookISBN>ISBN-12345678</bookISBN>
            <isLoaned>false</isLoaned>
        </bookInstance>
        <bookInstance>
            <inventoryNo>IN-1234569</inventoryNo>
            <bookISBN>ISBN-87654321</bookISBN>
            <isLoaned>true</isLoaned>
        </bookInstance>
    </bookInstances>
    <borrowings>
        <borrowing>
            <id>ID-8</id>
            <creationDate>2016-01-26</creationDate>
            <expirationDate>2016-03-21</expirationDate>
            <status>EXPIRED</status>
            <readerID>ID-6</readerID>
            <bookInstanceInventoryNo>IN-123456</bookInstanceInventoryNo>
        </borrowing>
        <borrowing>
            <id>ID-9</id>
            <creationDate>2017-01-23</creationDate>
            <expirationDate>2017-01-25</expirationDate>
            <status>RETURNED</status>
            <readerID>ID-6</readerID>
            <bookInstanceInventoryNo>IN-1234569</bookInstanceInventoryNo>
        </borrowing>
        <borrowing>
            <id>ID-10</id>
            <creationDate>2018-01-26</creationDate>
            <expirationDate>2018-05-11</expirationDate>
            <status>BORROWED</status>
            <readerID>ID-7</readerID>
            <bookInstanceInventoryNo>IN-1234569</bookInstanceInventoryNo>
        </borrowing>
    </borrowings>
</database>
